---
title: "W6D1_Fish"
format: html
---

Add libraries needed to explore the data

```{r}
install.packages('dplyr')
install.packages('tidyverse')
library(dplyr)
library(tidyr)
library(readr)
```

## Data Sources

Read the data from KNB Package Alaska commercial catches by management region (1886-1997)

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Explore Data

```{r}
##Prints the column names of the data frame
colnames(catch_original)
##First 6 lines of data frame
head(catch_original)
##Summary of each column of data
summary(catch_original)
## Prints unique values in a column (in this case region)
unique(catch_original$Region)
## Opens data frame in its own tab to see each row and column of the data (to be done in console)
```

# Using select() function

```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)

catch_data_2 <- catch_original %>% 
  select(-All,-notesRegCode)
```

## Quality Check

```{r}
##Quality Control: Glimpse is for visual and looks how it is supposed to 
dplyr::glimpse(catch_data)
```

# Check column types

```{r}
##This is not right 
##Mutate changes column names/creates new column 
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook)) #warning came up as N/A, some values missing 
head(catch_clean)
i <- which(is.na(catch_clean$Chinook))
```

```{r}
#This is the right way to do this 
catch_clean <- catch_data %>% 
  mutate(Chinook=if_else(condition = Chinook == 'I',
                         true = '1',
                         false = Chinook),
         Chinook = as.numeric(Chinook))
catch_clean[i, ]
    
```

#Catch Long

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(
    cols = -c(Region, Year),
    names_to = "species",
    values_to ='catch'
  )
head(catch_long)
```

# Catch Wide

```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from = species,
              values_from = catch)
head(catch_wide)
```

# Rename

```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch)

head(catch_long)
```

# Adding Columns Using Mutate

```{r}
catch_long <-  catch_long %>% 
  mutate(catch = catch_thousands *1000)
head(catch_long)
```

```{r}
catch_long <- catch_long %>% 
  mutate(catch = catch_thousands *1000) %>% 
  select(-catch_thousands)

head(catch_long)
```

# Summarize Statistics

```{r}
unique(catch_original$Region)
```

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch))
head(mean_region)
```

```{r}
n_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(n = n())
head(n_region)
```

# Filtering rows

```{r}
sse_catch <- catch_long %>% 
  filter(Region == 'SSE')
head(sse_catch)
```

# Sort Data

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(mean_catch)
head(mean_region)
```

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))
head(mean_region)
```

# Column Splitting

```{r}
sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAU-039"))
sites_df %>% 
  separate(site, c("isalnd",'site_number', '-'))
```

```{r}
dates_df <- data.frame(
  year = c("1930",
           "1930",
           "1930"), 
  month = c("12",
            "12",
            "12"),
  day = c("14",
          "15",
          "16")
)
dates_df %>% 
  unite(date, year, month, day, sep ='-')
```

# All together- A03
