project:
  type: website
  output-dir: .
  render:
    - index.qmd
    - assignments/a01_quarto_literate_analysis.qmd
    - assignments/intro_to_spatial_data.qmd
    - assignments/Samler_decision_log.qmd

website:
  title: "Sam Samler Portfolio"

format:
  html:
    toc: true

execute:
  echo: false
  warning: false
  message: false